# Generated by Django 5.1.1 on 2024-10-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='is_correct',
            field=models.BooleanField(help_text='Define if this is the correct answer to the question'),
        ),
    ]
