# Generated by Django 5.1.1 on 2024-10-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_choices_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoises',
            name='date_submited',
            field=models.DateTimeField(null=True),
        ),
    ]
