# Generated by Django 5.1.1 on 2024-11-19 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_userfunctionpermissions_is_obsolete'),
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='related_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permissions.function'),
        ),
    ]
