# Generated by Django 5.1.1 on 2024-10-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_userchoises_date_submited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchoises',
            name='quiz',
        ),
        migrations.AddField(
            model_name='userchoises',
            name='user_quiz',
            field=models.ForeignKey(default='d5734c29-464f-4772-bd99-20cd4b1489ca', on_delete=django.db.models.deletion.PROTECT, to='quiz.userquizscores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userquizscores',
            name='is_aproved',
            field=models.BooleanField(default=True, help_text='Stores if the user has passed the test'),
        ),
    ]
