# Generated by Django 5.1.1 on 2024-10-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_userchoises_quiz_userchoises_user_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizscores',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Stores if the user has passed the test'),
        ),
        migrations.AlterField(
            model_name='userquizscores',
            name='is_aproved',
            field=models.BooleanField(default=False, help_text='Stores if the user has passed the test'),
        ),
    ]
