# Generated by Django 5.1.1 on 2024-10-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_userquizscores_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoises',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete boolean'),
        ),
    ]
