# Generated by Django 5.1.1 on 2024-10-27 00:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_userchoises_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChoises',
            new_name='UserChoices',
        ),
    ]
