# Generated by Django 5.1.1 on 2024-10-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_rename_userchoises_userchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizscores',
            name='score',
            field=models.FloatField(help_text='The score of the user on the test, from 1 to 100.', null=True),
        ),
    ]
