# Generated by Django 5.1.1 on 2024-10-30 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfunctionpermissions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_permissions_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfunctionpermissions',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.function'),
        ),
        migrations.AddField(
            model_name='userfunctionpermissions',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_permissions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfunctionpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersectorpermissions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_permissions_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersectorpermissions',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_permissions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersectorpermissions',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.sector'),
        ),
        migrations.AddField(
            model_name='usersectorpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubsectorpermissions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsector_permissions_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubsectorpermissions',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsector_permissions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubsectorpermissions',
            name='subsector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.subsector'),
        ),
        migrations.AddField(
            model_name='usersubsectorpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
