# Generated by Django 5.1.1 on 2024-09-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_userpermissiontypes_userfunctionpermissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersectorpermissions',
            old_name='Subsector',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='usersubsectorpermissions',
            old_name='Subsector',
            new_name='subsector',
        ),
    ]
