# Generated by Django 5.1.1 on 2024-11-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_subsector_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='Subsector',
            new_name='subsector',
        ),
    ]
