# Generated by Django 5.1.1 on 2024-11-17 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_alter_function_subsector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='subsector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='permissions.subsector'),
        ),
    ]
