# Generated by Django 5.1.1 on 2024-11-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_alter_function_subsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfunctionpermissions',
            name='is_obsolete',
            field=models.BooleanField(default=False, help_text='When true, mark that the user does not need to review this function courses anymore'),
        ),
    ]
