# Generated by Django 5.1.1 on 2024-11-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursehistory',
            name='date_submited',
            field=models.DateTimeField(help_text='Date the user submited the course', null=True),
        ),
        migrations.AddField(
            model_name='usercoursehistory',
            name='end_date',
            field=models.DateTimeField(help_text='Date the user finished the course', null=True),
        ),
        migrations.AddField(
            model_name='usercoursehistory',
            name='expire_date',
            field=models.DateField(help_text='Date this couse expires, requiring the user to redo it', null=True),
        ),
        migrations.AddField(
            model_name='usercoursehistory',
            name='is_new_user',
            field=models.BooleanField(default=True, help_text='If true, it is the first time the user has done the course'),
        ),
        migrations.AddField(
            model_name='usercoursehistory',
            name='is_submited',
            field=models.BooleanField(default=False, help_text='Signals if the user agreed to submit the course has finished'),
        ),
        migrations.AddField(
            model_name='usercoursehistory',
            name='start_date',
            field=models.DateTimeField(help_text='Date of fisrt access of the user', null=True),
        ),
        migrations.AddField(
            model_name='usercoursehistory',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
