# Generated by Django 5.1.1 on 2024-11-17 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseclass'),
        ('permissions', '0006_alter_function_subsector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefunction',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_functions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='coursefunction',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_courses', to='permissions.function'),
        ),
    ]
