# Generated by Django 5.1.1 on 2024-11-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursefunction_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoursehistory',
            name='status',
        ),
    ]
