# Generated by Django 5.1.1 on 2024-11-20 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_usercoursehistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursehistory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='courses.course'),
        ),
    ]
