# Generated by Django 5.1.1 on 2024-09-18 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the function.', max_length=255)),
                ('description', models.TextField(help_text='Specify what the function is all about.')),
                ('is_active', models.BooleanField(help_text='Soft delete boolean')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the sector. Must be unique.', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Specify what part of the organization this sector represents.')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Title/Name of the course', max_length=255)),
                ('description', models.TextField(help_text='A description of the course. use it to signal what it teaches, how the user should aprouch it and whatever else you like')),
                ('expiration_time_in_days', models.IntegerField(default=365, help_text='\n        How long it will take for the course certification to expire in days.\n        If you want for it to not expire, set to a big number like: 99999\n        ')),
                ('required_for_function', models.BooleanField(default=True, help_text='\n        Defines if the course is needed for the function status to be set to "apt".\n        If true, the user can only be "apt" if this course is completed.\n        If false, this will be a complementary course, allowing the user to be "apt" even if not he has not compleated the course \n        ')),
                ('is_active', models.BooleanField(help_text='Soft delete boolean')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_courses', to=settings.AUTH_USER_MODEL)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.function')),
            ],
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the subsector.', max_length=255)),
                ('description', models.TextField(help_text='Specify what part of the sector this subsector represents.')),
                ('is_active', models.BooleanField(help_text='Soft delete boolean')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.sector')),
            ],
        ),
        migrations.AddField(
            model_name='function',
            name='Subsector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subsector'),
        ),
    ]
